pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: pan_joint
    joint_speed: 30.17
    motor: 
        id: 5
        init: 0
        max: 0
        min: 0

tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: tilt_joint
    joint_speed: 30.17
    motor:
        id: 6
        init: 512
        min: 0
        max: 0
